# Generated by Django 2.0.1 on 2018-02-12 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('telephone', models.IntegerField(unique=True)),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
