# Generated by Django 2.0.1 on 2018-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='telephone',
        ),
        migrations.AddField(
            model_name='applicants',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='username',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
